### ISSUE TITLE
ANNOUNCEMENT: This library will be discontinued in favor of the original angular-split

### ISSUE THREAD

**Issue by beeman** [beeman/ngx-split#10]
I've been added to https://github.com/bertrandg/angular-split as maintainer and will focus my efforts on maintaining that library. 

Please file any issues there.

Once I've released a stable version of `angular-split` that works with modern Angular versions, this repo will be archived.

**Comment by vitale232** [comment]
Glad to hear it. This is definitely the best outcome 👍

**Comment by beeman** [comment]
@vitale232 I totally agree. Super happy with it, less fragmentation is always good for the ecosystem!

**Comment by beeman** [comment]
angular-split v4.0.0 is released https://www.npmjs.com/package/angular-split/v/4.0.0 🎉
