### ISSUE TITLE
Cant use it in Angular 10

### ISSUE THREAD

**Issue by Rajdeep97** [beeman/ngx-split#8]
Thank you for forking & updating the module.

But I am having problems getting it to work in Angular 10.

First, my package.json to give you idea of what I have (It's a bare-bones install):

```
{
  "name": "mlalgo",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.4",
    "@angular/common": "~10.0.4",
    "@angular/compiler": "~10.0.4",
    "@angular/core": "~10.0.4",
    "@angular/forms": "~10.0.4",
    "@angular/platform-browser": "~10.0.4",
    "@angular/platform-browser-dynamic": "~10.0.4",
    "@angular/router": "~10.0.4",
    "ngx-split": "^2.0.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.3",
    "@angular/cli": "~10.0.3",
    "@angular/compiler-cli": "~10.0.4",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
```
}

Next, I included it in app.module.ts:
![2020-07-21_00h00_58](https://user-images.githubusercontent.com/21958914/87972854-414b5900-cae5-11ea-9d91-4b81057f2028.png)

But I get the error **"ui-split' is not a known element"**:
![2020-07-21_00h02_50](https://user-images.githubusercontent.com/21958914/87973021-840d3100-cae5-11ea-9331-a6845f68764c.png)

The Error:
![2020-07-21_00h03_26](https://user-images.githubusercontent.com/21958914/87973070-99825b00-cae5-11ea-82bd-71fb2ccdb7ff.png)

Please provide help regarding this problem.

**Comment by beeman** [comment]
@Rajdeep97 today I've been added as a maintainer to the original library, `angular-split` and I'm going to focus the effort on updating that library. 

Could you please try if it works with `angular-split@4.0.0-beta.0` and if not, file an issue [here](https://github.com/bertrandg/angular-split)?

Sorry for the confusion.
