### ISSUE TITLE
Can't use in Angular 8

### ISSUE THREAD

**Issue by ideapad** [beeman/ngx-split#9]
Having issue with using it on angular 8 ("@angular/core": "^8.2.0"). 
Getting this error during project compilation:
`ERROR in C:/project/node_modules/ngx-split/fesm5/ngx-split.js 871:12-21
"export 'ɵɵadvance' was not found in '@angular/core'
ERROR in C:/project/node_modules/ngx-split/fesm5/ngx-split.js 865:32-43
"export 'ɵɵloadQuery' was not found in '@angular/core'`

**Comment by beeman** [comment]
Hi @ideapad , thanks for creating the issue.

This library is meant to be used with more recent Angular versions, I don't plan on supporting any earlier versions, sorry for the inconvenience.

I think your best bet is to use [angular-split](https://github.com/bertrandg/angular-split).
